@startuml RPC 
left to right direction

package "serve layer" {
  [node balancer]
  [access in 0]
  [access in 1]
  [access in 2]

  [node balancer] --> [access in 0]
  [node balancer] --> [access in 1]
  [node balancer] --> [access in 2]
}

skinparam package{
    FontSize 13
    BorderColor blue
}

package "service" {
  [service handler]
  [router] 
}

package "local queue " #skyblue {
  [client local queue] 
  [client network queue]
}

package "tcp queue" #skyblue {
  [server network queue] 
  [server local queue]
}

package "network card layer"{
[client network card]
[server network card]
}

package "tcp transport layer" {
  [client tcp]
  [server tcp]
}

[router] --> [client local queue]
[client local queue] --> [client network queue] 
[client network queue] --> [client tcp]
[client tcp] --> [client network card] 
[client network card] .up.|> [server network card] 


[server network card] -left-> [server tcp]
[server tcp] -left-> [server network queue]
[server network queue] -left-> [server local queue]
[server local queue] --> [service handler]

[access in 0] --> [router]


@enduml