indent_style = "Block"
reorder_imports = true
max_width = 80
control_brace_style = "AlwaysSameLine"
edition = "2021"
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
normalize_comments = true
wrap_comments = true
comment_width = 80
