[package]
name = "rs_le"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="rs_le"
path="src/lib.rs"
proc-macro=true

[dependencies]
quote = "*"
syn = { version = "*", features = ["full"] }

[dev-dependencies]
trybuild = "1.0"
