name: leetcode.rs

# Run this workflow every time a new commit pushed to your repository
on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cc-test:
    name: cc test case
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install cmake build-essential libbenchmark-dev clang-12 catch2 -y
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: PATH
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
      - run: |
          cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -B build && cmake --build build -j $(nproc) && make -C build test -j $(nproc)
