name: cangjie

# Run this workflow every time a new commit pushed to your repository
on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cc-test:
    name: cangjie unit test
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install cmake build-essential clang -y
      - uses: Zxilly/setup-cangjie@v1
        with:
          channel: sts # 'canary' 或者 'sts'
          version: latest # 需要安装的仓颉版本，例如 0.53.13, 0.58.3，使用 latest 表示最新版，默认为 auto
          token: ${{ secrets.GITCODE_TOKEN }} # 访问仓颉 gitcode 仓库的 token，使用 canary 通道时必须提供
          tool-cache: true # 把编译 SDK 保存到 GitHub Actions 缓存中
      - run: |
          cjpm test
