name: leetcode.rs

# Run this workflow every time a new commit pushed to your repository
on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo test --benches -j$(nproc)

  clippy-test:
    name: cargo clippy
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: |
          cargo clippy -- -Dclippy::pedantic  -Aclippy::cast-lossless -Aclippy::cast-possible-truncation -Aclippy::cast-possible-wrap -Aclippy::cast-precision-loss -Aclippy::cast-sign-loss -Aclippy::checked-conversions

  miri-test:
    name: cargo miri
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - run: |
         list=();
         for p in $(find . -name "*.rs" ); do 
            num=$(grep unsafe $p | wc -l )
            if [[ $num -gt 0 ]]; then 
            # ./src/classic/link_list.rs
                val=$(echo $p  | sed 's/\.\/rs\///' \
                | sed 's/\.rs//' \
                | sed 's/\.//'  \
                | sed 's/\//::/g')
                list=(${list[*]} $val)
            fi
         done ; echo ${list[*]};
         MIRIFLAGS="-Zmiri-disable-isolation -Zmiri-ignore-leaks" cargo +nightly miri test -j$(nproc)  -- $(echo ${list[*]})

  rs-outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/install@cargo-outdated
      - run: cargo update
      - run: cargo outdated --workspace --exit-code 1
